local source = debug.getinfo(1, "S").source:sub(2)
local root = vim.fn.fnamemodify(source, ":p:h:h")
vim.opt.runtimepath:prepend(root)
local provider = require("herdr-agents.terminal").provider()
assert(not provider.paste("not running"))
local original = vim.api.nvim_get_current_win()
assert(provider.open("sh -c 'cat'", {}, nil, false))
assert(vim.api.nvim_get_current_win() == original)
local buffer = provider.pane()
assert(buffer and vim.bo[buffer].buftype == "terminal")
provider.focus()
assert(vim.api.nvim_get_current_buf() == buffer)
vim.cmd("stopinsert")
assert(provider.submit("test message", { focus = false }))
provider.close()
assert(not provider.pane())
assert(not vim.api.nvim_buf_is_valid(buffer))
print("herdr-agents terminal test passed")
vim.cmd("qa!")
